services:
  - type: web
    name: magical-market-game
    env: static
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: VITE_GAME_ENV
        value: production
      - key: VITE_APP_NAME
        value: Mystical Path
      - key: VITE_GAME_VERSION
        value: 1.3.0
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
